/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TransportCardsRouteImport } from './routes/transport-cards'
import { Route as SystemLogsRouteImport } from './routes/system-logs'
import { Route as SystemInfoRouteImport } from './routes/system-info'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TransportCardsIndexRouteImport } from './routes/transport-cards/index'
import { Route as SystemLogsIndexRouteImport } from './routes/system-logs/index'
import { Route as SystemInfoIndexRouteImport } from './routes/system-info/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MoneyStatisticIndexRouteImport } from './routes/money-statistic/index'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as BackupsIndexRouteImport } from './routes/backups/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as TransportCardsNewRouteImport } from './routes/transport-cards/new'
import { Route as TransportCardsCardIdRouteImport } from './routes/transport-cards/$cardId'
import { Route as RolesNewRouteImport } from './routes/roles/new'
import { Route as RolesRoleIdRouteImport } from './routes/roles/$roleId'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as DriversNewRouteImport } from './routes/drivers/new'
import { Route as DriversDriverIdRouteImport } from './routes/drivers/$driverId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as CarsNewRouteImport } from './routes/cars/new'
import { Route as CarsCarIdRouteImport } from './routes/cars/$carId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportCardsRoute = TransportCardsRouteImport.update({
  id: '/transport-cards',
  path: '/transport-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemLogsRoute = SystemLogsRouteImport.update({
  id: '/system-logs',
  path: '/system-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemInfoRoute = SystemInfoRouteImport.update({
  id: '/system-info',
  path: '/system-info',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const TransportCardsIndexRoute = TransportCardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransportCardsRoute,
} as any)
const SystemLogsIndexRoute = SystemLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemLogsRoute,
} as any)
const SystemInfoIndexRoute = SystemInfoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemInfoRoute,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RolesRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyStatisticIndexRoute = MoneyStatisticIndexRouteImport.update({
  id: '/money-statistic/',
  path: '/money-statistic/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriversRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarsRoute,
} as any)
const BackupsIndexRoute = BackupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackupsRoute,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const TransportCardsNewRoute = TransportCardsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransportCardsRoute,
} as any)
const TransportCardsCardIdRoute = TransportCardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => TransportCardsRoute,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RolesRoute,
} as any)
const RolesRoleIdRoute = RolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => RolesRoute,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversNewRoute = DriversNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DriversRoute,
} as any)
const DriversDriverIdRoute = DriversDriverIdRouteImport.update({
  id: '/$driverId',
  path: '/$driverId',
  getParentRoute: () => DriversRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsNewRoute = CarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CarsRoute,
} as any)
const CarsCarIdRoute = CarsCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => CarsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/drivers': typeof DriversRouteWithChildren
  '/login': typeof LoginRoute
  '/roles': typeof RolesRouteWithChildren
  '/system-info': typeof SystemInfoRouteWithChildren
  '/system-logs': typeof SystemLogsRouteWithChildren
  '/transport-cards': typeof TransportCardsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/new': typeof CarsNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/drivers/new': typeof DriversNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/roles/new': typeof RolesNewRoute
  '/transport-cards/$cardId': typeof TransportCardsCardIdRoute
  '/transport-cards/new': typeof TransportCardsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/backups/': typeof BackupsIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/money-statistic/': typeof MoneyStatisticIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/system-info/': typeof SystemInfoIndexRoute
  '/system-logs/': typeof SystemLogsIndexRoute
  '/transport-cards/': typeof TransportCardsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/new': typeof CarsNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/drivers/new': typeof DriversNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/roles/new': typeof RolesNewRoute
  '/transport-cards/$cardId': typeof TransportCardsCardIdRoute
  '/transport-cards/new': typeof TransportCardsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/backups': typeof BackupsIndexRoute
  '/cars': typeof CarsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/money-statistic': typeof MoneyStatisticIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/roles': typeof RolesIndexRoute
  '/system-info': typeof SystemInfoIndexRoute
  '/system-logs': typeof SystemLogsIndexRoute
  '/transport-cards': typeof TransportCardsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/drivers': typeof DriversRouteWithChildren
  '/login': typeof LoginRoute
  '/roles': typeof RolesRouteWithChildren
  '/system-info': typeof SystemInfoRouteWithChildren
  '/system-logs': typeof SystemLogsRouteWithChildren
  '/transport-cards': typeof TransportCardsRouteWithChildren
  '/users': typeof UsersRouteWithChildren
  '/cars/$carId': typeof CarsCarIdRoute
  '/cars/new': typeof CarsNewRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/drivers/new': typeof DriversNewRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/roles/$roleId': typeof RolesRoleIdRoute
  '/roles/new': typeof RolesNewRoute
  '/transport-cards/$cardId': typeof TransportCardsCardIdRoute
  '/transport-cards/new': typeof TransportCardsNewRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/users/new': typeof UsersNewRoute
  '/backups/': typeof BackupsIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/money-statistic/': typeof MoneyStatisticIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/system-info/': typeof SystemInfoIndexRoute
  '/system-logs/': typeof SystemLogsIndexRoute
  '/transport-cards/': typeof TransportCardsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/cars'
    | '/drivers'
    | '/login'
    | '/roles'
    | '/system-info'
    | '/system-logs'
    | '/transport-cards'
    | '/users'
    | '/cars/$carId'
    | '/cars/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/roles/$roleId'
    | '/roles/new'
    | '/transport-cards/$cardId'
    | '/transport-cards/new'
    | '/users/$userId'
    | '/users/new'
    | '/backups/'
    | '/cars/'
    | '/clients/'
    | '/drivers/'
    | '/money-statistic/'
    | '/orders/'
    | '/roles/'
    | '/system-info/'
    | '/system-logs/'
    | '/transport-cards/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cars/$carId'
    | '/cars/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/roles/$roleId'
    | '/roles/new'
    | '/transport-cards/$cardId'
    | '/transport-cards/new'
    | '/users/$userId'
    | '/users/new'
    | '/backups'
    | '/cars'
    | '/clients'
    | '/drivers'
    | '/money-statistic'
    | '/orders'
    | '/roles'
    | '/system-info'
    | '/system-logs'
    | '/transport-cards'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/cars'
    | '/drivers'
    | '/login'
    | '/roles'
    | '/system-info'
    | '/system-logs'
    | '/transport-cards'
    | '/users'
    | '/cars/$carId'
    | '/cars/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/drivers/$driverId'
    | '/drivers/new'
    | '/orders/$orderId'
    | '/orders/new'
    | '/roles/$roleId'
    | '/roles/new'
    | '/transport-cards/$cardId'
    | '/transport-cards/new'
    | '/users/$userId'
    | '/users/new'
    | '/backups/'
    | '/cars/'
    | '/clients/'
    | '/drivers/'
    | '/money-statistic/'
    | '/orders/'
    | '/roles/'
    | '/system-info/'
    | '/system-logs/'
    | '/transport-cards/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRouteWithChildren
  CarsRoute: typeof CarsRouteWithChildren
  DriversRoute: typeof DriversRouteWithChildren
  LoginRoute: typeof LoginRoute
  RolesRoute: typeof RolesRouteWithChildren
  SystemInfoRoute: typeof SystemInfoRouteWithChildren
  SystemLogsRoute: typeof SystemLogsRouteWithChildren
  TransportCardsRoute: typeof TransportCardsRouteWithChildren
  UsersRoute: typeof UsersRouteWithChildren
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  MoneyStatisticIndexRoute: typeof MoneyStatisticIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport-cards': {
      id: '/transport-cards'
      path: '/transport-cards'
      fullPath: '/transport-cards'
      preLoaderRoute: typeof TransportCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-logs': {
      id: '/system-logs'
      path: '/system-logs'
      fullPath: '/system-logs'
      preLoaderRoute: typeof SystemLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-info': {
      id: '/system-info'
      path: '/system-info'
      fullPath: '/system-info'
      preLoaderRoute: typeof SystemInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/transport-cards/': {
      id: '/transport-cards/'
      path: '/'
      fullPath: '/transport-cards/'
      preLoaderRoute: typeof TransportCardsIndexRouteImport
      parentRoute: typeof TransportCardsRoute
    }
    '/system-logs/': {
      id: '/system-logs/'
      path: '/'
      fullPath: '/system-logs/'
      preLoaderRoute: typeof SystemLogsIndexRouteImport
      parentRoute: typeof SystemLogsRoute
    }
    '/system-info/': {
      id: '/system-info/'
      path: '/'
      fullPath: '/system-info/'
      preLoaderRoute: typeof SystemInfoIndexRouteImport
      parentRoute: typeof SystemInfoRoute
    }
    '/roles/': {
      id: '/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof RolesRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-statistic/': {
      id: '/money-statistic/'
      path: '/money-statistic'
      fullPath: '/money-statistic/'
      preLoaderRoute: typeof MoneyStatisticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof DriversRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof CarsRoute
    }
    '/backups/': {
      id: '/backups/'
      path: '/'
      fullPath: '/backups/'
      preLoaderRoute: typeof BackupsIndexRouteImport
      parentRoute: typeof BackupsRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/transport-cards/new': {
      id: '/transport-cards/new'
      path: '/new'
      fullPath: '/transport-cards/new'
      preLoaderRoute: typeof TransportCardsNewRouteImport
      parentRoute: typeof TransportCardsRoute
    }
    '/transport-cards/$cardId': {
      id: '/transport-cards/$cardId'
      path: '/$cardId'
      fullPath: '/transport-cards/$cardId'
      preLoaderRoute: typeof TransportCardsCardIdRouteImport
      parentRoute: typeof TransportCardsRoute
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof RolesRoute
    }
    '/roles/$roleId': {
      id: '/roles/$roleId'
      path: '/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof RolesRoleIdRouteImport
      parentRoute: typeof RolesRoute
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/new': {
      id: '/drivers/new'
      path: '/new'
      fullPath: '/drivers/new'
      preLoaderRoute: typeof DriversNewRouteImport
      parentRoute: typeof DriversRoute
    }
    '/drivers/$driverId': {
      id: '/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof DriversDriverIdRouteImport
      parentRoute: typeof DriversRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/new': {
      id: '/cars/new'
      path: '/new'
      fullPath: '/cars/new'
      preLoaderRoute: typeof CarsNewRouteImport
      parentRoute: typeof CarsRoute
    }
    '/cars/$carId': {
      id: '/cars/$carId'
      path: '/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof CarsCarIdRouteImport
      parentRoute: typeof CarsRoute
    }
  }
}

interface BackupsRouteChildren {
  BackupsIndexRoute: typeof BackupsIndexRoute
}

const BackupsRouteChildren: BackupsRouteChildren = {
  BackupsIndexRoute: BackupsIndexRoute,
}

const BackupsRouteWithChildren =
  BackupsRoute._addFileChildren(BackupsRouteChildren)

interface CarsRouteChildren {
  CarsCarIdRoute: typeof CarsCarIdRoute
  CarsNewRoute: typeof CarsNewRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsCarIdRoute: CarsCarIdRoute,
  CarsNewRoute: CarsNewRoute,
  CarsIndexRoute: CarsIndexRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface DriversRouteChildren {
  DriversDriverIdRoute: typeof DriversDriverIdRoute
  DriversNewRoute: typeof DriversNewRoute
  DriversIndexRoute: typeof DriversIndexRoute
}

const DriversRouteChildren: DriversRouteChildren = {
  DriversDriverIdRoute: DriversDriverIdRoute,
  DriversNewRoute: DriversNewRoute,
  DriversIndexRoute: DriversIndexRoute,
}

const DriversRouteWithChildren =
  DriversRoute._addFileChildren(DriversRouteChildren)

interface RolesRouteChildren {
  RolesRoleIdRoute: typeof RolesRoleIdRoute
  RolesNewRoute: typeof RolesNewRoute
  RolesIndexRoute: typeof RolesIndexRoute
}

const RolesRouteChildren: RolesRouteChildren = {
  RolesRoleIdRoute: RolesRoleIdRoute,
  RolesNewRoute: RolesNewRoute,
  RolesIndexRoute: RolesIndexRoute,
}

const RolesRouteWithChildren = RolesRoute._addFileChildren(RolesRouteChildren)

interface SystemInfoRouteChildren {
  SystemInfoIndexRoute: typeof SystemInfoIndexRoute
}

const SystemInfoRouteChildren: SystemInfoRouteChildren = {
  SystemInfoIndexRoute: SystemInfoIndexRoute,
}

const SystemInfoRouteWithChildren = SystemInfoRoute._addFileChildren(
  SystemInfoRouteChildren,
)

interface SystemLogsRouteChildren {
  SystemLogsIndexRoute: typeof SystemLogsIndexRoute
}

const SystemLogsRouteChildren: SystemLogsRouteChildren = {
  SystemLogsIndexRoute: SystemLogsIndexRoute,
}

const SystemLogsRouteWithChildren = SystemLogsRoute._addFileChildren(
  SystemLogsRouteChildren,
)

interface TransportCardsRouteChildren {
  TransportCardsCardIdRoute: typeof TransportCardsCardIdRoute
  TransportCardsNewRoute: typeof TransportCardsNewRoute
  TransportCardsIndexRoute: typeof TransportCardsIndexRoute
}

const TransportCardsRouteChildren: TransportCardsRouteChildren = {
  TransportCardsCardIdRoute: TransportCardsCardIdRoute,
  TransportCardsNewRoute: TransportCardsNewRoute,
  TransportCardsIndexRoute: TransportCardsIndexRoute,
}

const TransportCardsRouteWithChildren = TransportCardsRoute._addFileChildren(
  TransportCardsRouteChildren,
)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersNewRoute: typeof UsersNewRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersNewRoute: UsersNewRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRouteWithChildren,
  CarsRoute: CarsRouteWithChildren,
  DriversRoute: DriversRouteWithChildren,
  LoginRoute: LoginRoute,
  RolesRoute: RolesRouteWithChildren,
  SystemInfoRoute: SystemInfoRouteWithChildren,
  SystemLogsRoute: SystemLogsRouteWithChildren,
  TransportCardsRoute: TransportCardsRouteWithChildren,
  UsersRoute: UsersRouteWithChildren,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  MoneyStatisticIndexRoute: MoneyStatisticIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
